import { exec } from './logger';
import * as startWith from "./startWith";
import * as combineLatest from './combineLatest';
import * as merge from './merge';
import * as concat from './concat';
import * as forkJoin from './forkJoin';
import * as withLatestFrom from './withLatestFrom';
import * as zip from './zip';
import * as race from './race';
import * as pairwise from './pairwise';
import * as from from './from';
import * as of from './of';
import * as catchError from './catchError';
import * as retry from './retry';
import * as share from './share';
import * as shareReplay from './shareReplay';

// exec(startWith);
// exec(combineLatest);
// exec(merge);
// exec(concat);
// exec(forkJoin);
// exec(withLatestFrom);
// exec(zip);
// exec(race);
// exec(pairwise);
// exec(from);
// exec(of);
// exec(catchError);
// exec(retry);
// exec(share);
exec(shareReplay);
